### ISSUE TITLE
Service not being run on successful config check.

### ISSUE THREAD

**Issue by quexser** [custom-components/config_check#3]
When the config check is successful it isn't running the service call I've told it to do.

If I understand the readme correctly, I should be able to do this, and it should turn my sofa lamp off if the config check goes through successfully. 

![image](https://user-images.githubusercontent.com/44878741/63142428-bb12c280-bfb7-11e9-994e-7615c7d67aaf.png)

```json
{
  "service": "light.turn_off",
  "service_data": {
    "entity_id": "light.livingroom_sofalamp"
  }
}
```

When I run this, it puts the successful check in my persistent notifications but doesn't ever turn off the sofa lamp.

**Comment by BartEngelen** [comment]
Hello,
I have the same issue.
Kind regards,
Bart

**Comment by ludeeus** [comment]
Fixed in latest commit https://github.com/custom-components/config_check/commit/bcaeacc0542502b4ed3c37579d4d3c342b563cf0#diff-bf55903d57be6c1cafb921d77e588138L44
